name: Build and test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      salt-master:
        image: mbologna/saltstack-master
        options: --name saltmaster
        ports:
          - 8000:9080
      salt-minion1:
        image: mbologna/saltstack-minion
        options: --name saltminion1 --link saltmaster:salt
      salt-minion2:
        image: mbologna/saltstack-minion
        options: --name saltminion2 --link saltmaster:salt

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build and test with Maven
        run: mvn checkstyle:check javadoc:javadoc test package
